services: 
  web: 
    image: nginx:1.25-alpine
    container_name : ${PROJECT_NAME}_nginx
    ports: 
      - "80:80"
    volumes: 
      - "./www:/var/www/vide-grenier:rw"
      - ".docker/nginx/site.template:/etc/nginx/conf.d/site.template:ro"
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
    command: sh -c "envsubst '$$PROJECT_NAME' < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
  php:
    build: .docker/php
    container_name: ${PROJECT_NAME}_php
    working_dir: /var/www/${PROJECT_NAME}
    volumes:
      - "./www:/var/www/vide-grenier:rw"
    command: bash -c "composer install && php-fpm"

  db:
    image: mysql:8
    container_name: ${PROJECT_NAME}_db
    environment:
      MYSQL_DATABASE: "db-vide-grenier"
      MYSQL_USER: "vide-grenier"
      MYSQL_PASSWORD: "vide-grenier"
      MYSQL_ROOT_PASSWORD: "root"

    volumes:
      - "bdd_data:/var/lib/mysql"


  adminer:
    image: adminer:latest
    container_name: ${PROJECT_NAME}_adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  bdd_data: